import type { Stage, Surah } from "./types";

export const QURAN_SURAHS: Surah[] = [
  { number: 1, name: "الفاتحة" },
  { number: 2, name: "البقرة", pagesCount: 48 },
  { number: 3, name: "آل عمران", pagesCount: 27 },
  { number: 4, name: "النساء", pagesCount: 29 },
  { number: 5, name: "المائدة", pagesCount: 22 },
  { number: 6, name: "الأنعام", pagesCount: 23 },
  { number: 7, name: "الأعراف", pagesCount: 26 },
  { number: 8, name: "الأنفال", pagesCount: 10 },
  { number: 9, name: "التوبة", pagesCount: 21 },
  { number: 10, name: "يونس", pagesCount: 13 },
  { number: 11, name: "هود", pagesCount: 13 },
  { number: 12, name: "يوسف", pagesCount: 13 },
  { number: 13, name: "الرعد", pagesCount: 6 },
  { number: 14, name: "إبراهيم", pagesCount: 7 },
  { number: 15, name: "الحجر", pagesCount: 5 },
  { number: 16, name: "النحل", pagesCount: 14 },
  { number: 17, name: "الإسراء", pagesCount: 11 },
  { number: 18, name: "الكهف", pagesCount: 11 },
  { number: 19, name: "مريم", pagesCount: 7 },
  { number: 20, name: "طه", pagesCount: 9 },
  { number: 21, name: "الأنبياء", pagesCount: 10 },
  { number: 22, name: "الحج", pagesCount: 10 },
  { number: 23, name: "المؤمنون", pagesCount: 8 },
  { number: 24, name: "النور", pagesCount: 9 },
  { number: 25, name: "الفرقان", pagesCount: 7 },
  { number: 26, name: "الشعراء", pagesCount: 10 },
  { number: 27, name: "النمل", pagesCount: 9 },
  { number: 28, name: "القصص", pagesCount: 11 },
  { number: 29, name: "العنكبوت", pagesCount: 8 },
  { number: 30, name: "الروم", pagesCount: 6 },
  { number: 31, name: "لقمان", pagesCount: 4 },
  { number: 32, name: "السجدة", pagesCount: 3 },
  { number: 33, name: "الأحزاب", pagesCount: 10 },
  { number: 34, name: "سبأ", pagesCount: 6 },
  { number: 35, name: "فاطر", pagesCount: 6 },
  { number: 36, name: "يس", pagesCount: 6 },
  { number: 37, name: "الصافات", pagesCount: 7 },
  { number: 38, name: "ص", pagesCount: 5 },
  { number: 39, name: "الزمر", pagesCount: 9 },
  { number: 40, name: "غافر", pagesCount: 9 },
  { number: 41, name: "فصلت", pagesCount: 6 },
  { number: 42, name: "الشورى", pagesCount: 6 },
  { number: 43, name: "الزخرف", pagesCount: 7 },
  { number: 44, name: "الدخان", pagesCount: 3 },
  { number: 45, name: "الجاثية", pagesCount: 4 },
  { number: 46, name: "الأحقاف", pagesCount: 5 },
  { number: 47, name: "محمد", pagesCount: 4 },
  { number: 48, name: "الفتح", pagesCount: 5 },
  { number: 49, name: "الحجرات", pagesCount: 3 },
  { number: 50, name: "ق", pagesCount: 3 },
  { number: 51, name: "الذاريات", pagesCount: 3 },
  { number: 52, name: "الطور", pagesCount: 3 },
  { number: 53, name: "النجم", pagesCount: 3 },
  { number: 54, name: "القمر", pagesCount: 3 },
  { number: 55, name: "الرحمن", pagesCount: 3 },
  { number: 56, name: "الواقعة", pagesCount: 3 },
  { number: 57, name: "الحديد", pagesCount: 4 },
  { number: 58, name: "المجادلة", pagesCount: 3 },
  { number: 59, name: "الحشر", pagesCount: 4 },
  { number: 60, name: "الممتحنة", pagesCount: 3 },
  { number: 61, name: "الصف", pagesCount: 2 },
  { number: 62, name: "الجمعة", pagesCount: 2 },
  { number: 63, name: "المنافقون", pagesCount: 2 },
  { number: 64, name: "التغابن", pagesCount: 2 },
  { number: 65, name: "الطلاق", pagesCount: 2 },
  { number: 66, name: "التحريم", pagesCount: 2 },
  { number: 67, name: "الملك", pagesCount: 3 },
  { number: 68, name: "القلم", pagesCount: 2 },
  { number: 69, name: "الحاقة", pagesCount: 2 },
  { number: 70, name: "المعارج", pagesCount: 2 },
  { number: 71, name: "نوح", pagesCount: 2 },
  { number: 72, name: "الجن", pagesCount: 2 },
  { number: 73, name: "المزمل", pagesCount: 2 },
  { number: 74, name: "المدثر", pagesCount: 2 },
  { number: 75, name: "القيامة", pagesCount: 2 },
  { number: 76, name: "الإنسان", pagesCount: 2 },
  { number: 77, name: "المرسلات", pagesCount: 2 },
  { number: 78, name: "النبأ", pagesCount: 2 },
  { number: 79, name: "النازعات", pagesCount: 2 },
  { number: 80, name: "عبس" },
  { number: 81, name: "التكوير" },
  { number: 82, name: "الانفطار" },
  { number: 83, name: "المطففين" },
  { number: 84, name: "الانشقاق" },
  { number: 85, name: "البروج" },
  { number: 86, name: "الطارق" },
  { number: 87, name: "الأعلى" },
  { number: 88, name: "الغاشية" },
  { number: 89, name: "الفجر" },
  { number: 90, name: "البلد" },
  { number: 91, name: "الشمس" },
  { number: 92, name: "الليل" },
  { number: 93, name: "الضحى" },
  { number: 94, name: "الشرح" },
  { number: 95, name: "التين" },
  { number: 96, name: "العلق" },
  { number: 97, name: "القدر" },
  { number: 98, name: "البينة" },
  { number: 99, name: "الزلزلة" },
  { number: 100, name: "العاديات" },
  { number: 101, name: "القارعة" },
  { number: 102, name: "التكاثر" },
  { number: 103, name: "العصر" },
  { number: 104, name: "الهمزة" },
  { number: 105, name: "الفيل" },
  { number: 106, name: "قريش" },
  { number: 107, name: "الماعون" },
  { number: 108, name: "الكوثر" },
  { number: 109, name: "الكافرون" },
  { number: 110, name: "النصر" },
  { number: 111, name: "المسد" },
  { number: 112, name: "الإخلاص" },
  { number: 113, name: "الفلق" },
  { number: 114, name: "الناس" },
];

export const STAGES: Stage[] = [
  { level: 1, name: "مرحلة البذرة", minXP: 0, maxXP: 1000, description: "بداية مباركة ونبتة صالحة في رياض المعرفة.", badgeIcon: "eco" },
  { level: 2, name: "مرحلة الشتلة", minXP: 1001, maxXP: 3000, description: "تنمو المعرفة وتترسخ خطى الحفظ في القلوب.", badgeIcon: "yard" },
  { level: 3, name: "مرحلة الغصن", minXP: 3001, maxXP: 6000, description: "غصن يافع يرتوي بالقرآن والسنة واللغة النافعة.", badgeIcon: "nature" },
  { level: 4, name: "مرحلة الشجرة المثمرة", minXP: 6001, maxXP: 10000, description: "أثمر السعي والجد، وبدأت الحكمة تظهر.", badgeIcon: "local_florist" },
  { level: 5, name: "مرحلة الظل الممتد", minXP: 10001, maxXP: 999999, description: "تاج الحافظين، يظلل من حوله بنور وسكينة وعلم واسع.", badgeIcon: "park" },
];

export const AVATAR_MAP: Record<string, string> = {
  "avatar-leaf": "🌿",
  "avatar-mountain": "🏔️",
  "avatar-sun": "☀️",
  "avatar-flower": "🌸",
  "avatar-water": "💧",
  "avatar-shield": "🛡️",
};

export const AVATAR_OPTIONS = [
  { value: "avatar-leaf", label: "غصن أخضر", emoji: "🌿" },
  { value: "avatar-mountain", label: "جبل الحكمة", emoji: "🏔️" },
  { value: "avatar-sun", label: "شمس الهداية", emoji: "☀️" },
  { value: "avatar-flower", label: "زهرة الأخلاق", emoji: "🌸" },
  { value: "avatar-water", label: "غيث المعرفة", emoji: "💧" },
  { value: "avatar-shield", label: "درع العقيدة", emoji: "🛡️" },
];

export function getAvatarEmoji(avatar: string): string {
  return AVATAR_MAP[avatar] ?? "🌸";
}

export const ICON_MAP: Record<string, string> = {
  add: "plus",
  add_box: "square-plus",
  add_circle: "circle-plus",
  arrow_back: "arrow-left",
  auto_stories: "book-open",
  cancel: "circle-x",
  check: "check",
  check_circle: "circle-check-big",
  check_circle_outline: "circle-check",
  close: "circle-x",
  delete: "trash-2",
  done_all: "check-check",
  eco: "leaf",
  edit: "pen",
  edit_note: "file-pen",
  emoji_events: "trophy",
  error: "triangle-alert",
  error_outline: "triangle-alert",
  expand_more: "chevron-down",
  folder: "folder",
  groups: "users",
  home: "house",
  library_books: "library",
  lightbulb: "lightbulb",
  list_alt: "list-ordered",
  lock: "lock",
  login: "log-in",
  logout: "log-out",
  manage_accounts: "user-cog",
  menu: "menu",
  menu_book: "book-open",
  military_tech: "award",
  park: "trees",
  people: "users",
  person: "user",
  person_add: "user-plus",
  psychology: "brain",
  query_stats: "chart-column",
  restart_alt: "rotate-ccw",
  search: "search",
  spa: "flower-2",
  stars: "sparkles",
  sync: "refresh-cw",
  translate: "languages",
  trending_up: "trending-up",
  verified: "badge-check",
  visibility: "eye",
  visibility_off: "eye-off",
  warning: "circle-alert",
  wb_sunny: "sun",
  yard: "trees",
  nature: "trees",
  local_florist: "flower-2",
};

export function getLucideIconName(name: string): string {
  return ICON_MAP[name] || name;
}
