interface VocabWord {
  word: string;
  definition: string;
}

export interface VocabUnit {
  unit: number;
  words: VocabWord[];
}

export const VOCAB_DATA: VocabUnit[] = [
  {
    unit: 1,
    words: [
      { word: 'afraid', definition: 'When someone is afraid, they feel fear.' },
      { word: 'agree', definition: 'To agree is to say "yes" or to think the same way.' },
      { word: 'angry', definition: 'When someone is angry, they may want to speak loudly or fight.' },
      { word: 'arrive', definition: 'To arrive is to get to or reach some place.' },
      { word: 'attack', definition: 'To attack is to try to fight or to hurt.' },
      { word: 'bottom', definition: 'The bottom is the lowest part.' },
      { word: 'clever', definition: 'When someone is clever, they can solve a hard puzzle or problem.' },
      { word: 'cruel', definition: 'When someone is cruel, they do bad things to hurt others.' },
      { word: 'finally', definition: 'If something happens finally, it happens after a long time or at the end.' },
      { word: 'hide', definition: 'To hide is to try not to let others see you.' },
      { word: 'hunt', definition: 'To hunt is to look for or search for an animal to kill.' },
      { word: 'lot', definition: 'A lot means a large number or amount of people, animals, things, etc.' },
      { word: 'middle', definition: 'The middle of something is the center or halfway point.' },
      { word: 'moment', definition: 'A moment is a second or a very short time.' },
      { word: 'pleased', definition: 'When someone is pleased, they are happy.' },
      { word: 'promise', definition: 'To promise is to say you will do something for sure.' },
      { word: 'reply', definition: 'To reply is to give an answer or say back to someone.' },
      { word: 'safe', definition: 'When a person is safe, they are not in danger.' },
      { word: 'trick', definition: 'A trick is something you do to fool another person.' },
      { word: 'well', definition: 'You use well to say that something was done in a good way.' },
    ],
  },
  {
    unit: 2,
    words: [
      { word: 'adventure', definition: 'An adventure is a fun or exciting thing that you do.' },
      { word: 'approach', definition: 'To approach something means to move close to it.' },
      { word: 'carefully', definition: 'Carefully means with great attention, especially to detail or safety.' },
      { word: 'chemical', definition: 'A chemical is something that scientists use in chemistry.' },
      { word: 'create', definition: 'To create means to make something new.' },
      { word: 'evil', definition: 'Evil describes something or someone bad or cruel, not good.' },
      { word: 'experiment', definition: 'An experiment is a test that you do to see what will happen.' },
      { word: 'kill', definition: 'To kill someone or something is to make them die.' },
      { word: 'laboratory', definition: 'A laboratory is a room where a scientist works.' },
      { word: 'laugh', definition: 'Laugh is the sound made when someone is happy or a funny thing occurs.' },
      { word: 'loud', definition: 'If a sound is loud, it is strong and very easy to hear.' },
      { word: 'nervous', definition: 'When a person is nervous, they think something bad will happen.' },
      { word: 'noise', definition: 'A noise is an unpleasant sound.' },
      { word: 'project', definition: 'A project is a type of work that you do for school or a job.' },
      { word: 'scare', definition: 'To scare someone is to make them feel afraid.' },
      { word: 'secret', definition: 'A secret is something that you do not tell other people.' },
      { word: 'shout', definition: 'To shout is to say something loudly.' },
      { word: 'smell', definition: 'To smell something means to use your nose to sense it.' },
      { word: 'terrible', definition: 'If something is terrible, it is very bad.' },
      { word: 'worse', definition: 'If something is worse, it is of poorer quality than another thing.' },
    ],
  },
  {
    unit: 3,
    words: [
      { word: 'alien', definition: 'An alien is a creature from a different world.' },
      { word: 'among', definition: 'If you are among certain things, they are all around you.' },
      { word: 'chart', definition: 'A chart is a list of information.' },
      { word: 'cloud', definition: 'A cloud is a group of water drops in the sky.' },
      { word: 'comprehend', definition: 'To comprehend something is to understand it.' },
      { word: 'describe', definition: 'To describe is to say or write what someone or something is like.' },
      { word: 'ever', definition: 'Ever means at any time.' },
      { word: 'fail', definition: 'To fail means you do not succeed in what you try to do.' },
      { word: 'friendly', definition: 'Friendly is behaving in a pleasant, kind way toward someone.' },
      { word: 'grade', definition: 'A grade is a score or mark given to someone\'s work.' },
      { word: 'instead', definition: 'Instead means in place of.' },
      { word: 'library', definition: 'A library is a place where you go to read books.' },
      { word: 'planet', definition: 'A planet is a large round thing in space.' },
      { word: 'report', definition: 'A report is something students write for school.' },
      { word: 'several', definition: 'Several is more than two but not many.' },
      { word: 'solve', definition: 'To solve something is to find an answer to it.' },
      { word: 'suddenly', definition: 'If something happens suddenly, it happens quickly and unexpectedly.' },
      { word: 'suppose', definition: 'To suppose is to guess.' },
      { word: 'universe', definition: 'The universe is the known or supposed objects in space.' },
      { word: 'view', definition: 'To view is to look at something.' },
    ],
  },
  {
    unit: 4,
    words: [
      { word: 'appropriate', definition: 'When a thing is appropriate, it is right or normal.' },
      { word: 'avoid', definition: 'To avoid something is to stay away from it.' },
      { word: 'behave', definition: 'To behave is to act in a particular way, especially to be good.' },
      { word: 'calm', definition: 'When someone is calm, they do not get excited or upset.' },
      { word: 'concern', definition: 'Concern is a feeling of worry.' },
      { word: 'content', definition: 'To be content is to be happy and not want more.' },
      { word: 'expect', definition: 'If you expect something to happen, you believe it will happen.' },
      { word: 'frequently', definition: 'When something happens frequently, it happens often.' },
      { word: 'habit', definition: 'A habit is a thing that you do often.' },
      { word: 'instruct', definition: 'To instruct is to teach.' },
      { word: 'issue', definition: 'An issue is an important topic.' },
      { word: 'none', definition: 'None means not any of someone or something.' },
      { word: 'patient', definition: 'If a person is patient, they don\'t become angry or upset easily.' },
      { word: 'positive', definition: 'If something is positive, it is good.' },
      { word: 'punish', definition: 'To punish means to make someone suffer for breaking the rules or laws.' },
      { word: 'represent', definition: 'To represent is to speak or act for a person or group.' },
      { word: 'shake', definition: 'To shake is to move back and forth or up and down quickly.' },
      { word: 'spread', definition: 'To spread is to move quickly to more places.' },
      { word: 'stroll', definition: 'To stroll means to walk slowly and calmly.' },
      { word: 'village', definition: 'A village is a very small town.' },
    ],
  },
  {
    unit: 5,
    words: [
      { word: 'aware', definition: 'If you are aware of something, you know about it.' },
      { word: 'badly', definition: 'Badly means in a severe or harmful way.' },
      { word: 'belong', definition: 'If something belongs to you, you own it.' },
      { word: 'continue', definition: 'To continue something is to keep doing it.' },
      { word: 'error', definition: 'An error is something you do wrong.' },
      { word: 'experience', definition: 'An experience is something you have seen or done.' },
      { word: 'field', definition: 'A field is a big area of land.' },
      { word: 'hurt', definition: 'To hurt is to do something that makes you feel pain.' },
      { word: 'judgment', definition: 'Judgment is the ability to form opinions or decisions.' },
      { word: 'likely', definition: 'If something likely happens, it will probably happen.' },
      { word: 'normal', definition: 'If something is normal, it is not strange nor surprising to you.' },
      { word: 'rare', definition: 'If something is rare, you do not see it very often.' },
      { word: 'relax', definition: 'To relax is to rest.' },
      { word: 'request', definition: 'To request something is to ask for it.' },
      { word: 'reside', definition: 'To reside means to live somewhere permanently or for a long time.' },
      { word: 'result', definition: 'A result is something that happens because of something else.' },
      { word: 'roll', definition: 'To roll is to move by turning over and over.' },
      { word: 'since', definition: 'Since is used to talk about a past event still happening now.' },
      { word: 'visible', definition: 'If something is visible, it can be seen.' },
      { word: 'wild', definition: 'If something is wild, it is found in nature.' },
    ],
  },
  {
    unit: 6,
    words: [
      { word: 'advantage', definition: 'An advantage is something that helps you.' },
      { word: 'cause', definition: 'To cause is to make something happen.' },
      { word: 'choice', definition: 'A choice is the act or possibility of picking something.' },
      { word: 'community', definition: 'A community is a group of people who live together.' },
      { word: 'dead', definition: 'To be dead is to not be alive.' },
      { word: 'distance', definition: 'The distance between two things is how far it is between them.' },
      { word: 'escape', definition: 'To escape is to run away from something bad.' },
      { word: 'face', definition: 'If you face a problem, you deal with it.' },
      { word: 'follow', definition: 'To follow means to go behind someone and go where they go.' },
      { word: 'fright', definition: 'Fright is the feeling of being scared.' },
      { word: 'ghost', definition: 'A ghost is the spirit of a dead person.' },
      { word: 'individual', definition: 'An individual is one person.' },
      { word: 'pet', definition: 'A pet is an animal that lives with people.' },
      { word: 'reach', definition: 'To reach means to arrive at a place.' },
      { word: 'return', definition: 'To return is to go back to a place.' },
      { word: 'survive', definition: 'To survive is to stay alive.' },
      { word: 'upset', definition: 'To be upset is to be unhappy about something.' },
      { word: 'voice', definition: 'A voice is the sound a person makes when they talk or sing.' },
      { word: 'weather', definition: 'The weather is the condition of the air: hot, rainy, windy, etc.' },
      { word: 'wise', definition: 'To be wise is to use experience and intelligence to make good choices.' },
    ],
  },
  {
    unit: 7,
    words: [
      { word: 'allow', definition: 'To allow something to happen means to let it happen.' },
      { word: 'announce', definition: 'To announce something is to make it known.' },
      { word: 'beside', definition: 'When someone or something is beside you, they are next to you.' },
      { word: 'challenge', definition: 'A challenge is something difficult to complete.' },
      { word: 'claim', definition: 'To claim means to say that something is true.' },
      { word: 'condition', definition: 'The condition of someone or something is the state that they are in.' },
      { word: 'contribute', definition: 'To contribute to something means to do something to make it successful.' },
      { word: 'difference', definition: 'A difference is a way that something is not like other things.' },
      { word: 'divide', definition: 'To divide something is to make it into smaller parts.' },
      { word: 'expert', definition: 'An expert is someone who is very good at doing something.' },
      { word: 'famous', definition: 'If someone or something is famous, they are known to many people.' },
      { word: 'force', definition: 'Force is a person\'s strength or power.' },
      { word: 'harm', definition: 'Harm is hurt or problems caused to someone or something.' },
      { word: 'lay', definition: 'To lay means to put or place in a horizontal or flat position.' },
      { word: 'peace', definition: 'Peace is a time without war.' },
      { word: 'prince', definition: 'A prince is the son of a king.' },
      { word: 'protect', definition: 'To protect someone is to stop them from getting hurt.' },
      { word: 'sense', definition: 'To sense something is to know about it without being told.' },
      { word: 'sudden', definition: 'When something is sudden, it happens very quickly.' },
      { word: 'therefore', definition: 'Therefore means for this reason.' },
    ],
  },
  {
    unit: 8,
    words: [
      { word: 'accept', definition: 'To accept something that is offered is to take it.' },
      { word: 'arrange', definition: 'To arrange things is to put them in the right place.' },
      { word: 'attend', definition: 'To attend something is to go to it.' },
      { word: 'balance', definition: 'To balance something is to keep it from falling.' },
      { word: 'contrast', definition: 'A contrast is the sharp difference between two things.' },
      { word: 'encourage', definition: 'To encourage someone is to make them want to do something.' },
      { word: 'familiar', definition: 'If someone or something is familiar to you, you know them well.' },
      { word: 'grab', definition: 'To grab is to take a hold of someone or something suddenly.' },
      { word: 'hang', definition: 'To hang something is to keep it above the ground.' },
      { word: 'huge', definition: 'If something is huge, it is very big.' },
      { word: 'necessary', definition: 'If something is necessary, you must do it.' },
      { word: 'pattern', definition: 'A pattern is a way in which something is done or organized.' },
      { word: 'propose', definition: 'To propose something is to say that it should be done.' },
      { word: 'purpose', definition: 'A purpose is the reason that you do something.' },
      { word: 'release', definition: 'To release something is to stop holding it.' },
      { word: 'require', definition: 'To require something is to say that it is necessary.' },
      { word: 'single', definition: 'If something is single, then there is only one.' },
      { word: 'success', definition: 'Success is doing something well that you choose to do.' },
      { word: 'tear', definition: 'To tear something means to pull it apart.' },
      { word: 'theory', definition: 'A theory is an idea about how something works.' },
    ],
  },
  {
    unit: 9,
    words: [
      { word: 'against', definition: 'To be against something is to be touching it or opposed to it.' },
      { word: 'beach', definition: 'The beach is a sandy or rocky place by the ocean.' },
      { word: 'damage', definition: 'To damage something is to break it.' },
      { word: 'discover', definition: 'To discover something is to find it for the first time.' },
      { word: 'emotion', definition: 'An emotion is how you feel.' },
      { word: 'fix', definition: 'To fix something is to make it work.' },
      { word: 'frank', definition: 'If you are frank, you are being very honest.' },
      { word: 'identify', definition: 'To identify something is to be able to name it.' },
      { word: 'island', definition: 'An island is land in the middle of water.' },
      { word: 'ocean', definition: 'The ocean is all of the salt water that surrounds land.' },
      { word: 'perhaps', definition: 'Perhaps is used when you say that something could happen.' },
      { word: 'pleasant', definition: 'If something is pleasant, you enjoy it.' },
      { word: 'prevent', definition: 'To prevent something is to stop it from happening.' },
      { word: 'rock', definition: 'A rock is a hard thing in the dirt.' },
      { word: 'save', definition: 'To save something is to keep it from being hurt.' },
      { word: 'step', definition: 'To step is to walk.' },
      { word: 'still', definition: 'Still is used when you say that a situation keeps going on.' },
      { word: 'taste', definition: 'A taste is the flavor something makes in your mouth.' },
      { word: 'throw', definition: 'To throw something is to use your hand to make it go through the air.' },
      { word: 'wave', definition: 'A wave is a line of water that moves higher than the rest of the water.' },
    ],
  },
  {
    unit: 10,
    words: [
      { word: 'benefit', definition: 'A benefit is a good thing.' },
      { word: 'certain', definition: 'If you are certain about something, you know it is true.' },
      { word: 'chance', definition: 'A chance is an opportunity to do something.' },
      { word: 'effect', definition: 'An effect is a change made by something else.' },
      { word: 'essential', definition: 'If something is essential, it is very important and necessary.' },
      { word: 'far', definition: 'If something is far, it is not close.' },
      { word: 'focus', definition: 'To focus on something is to think about it and pay attention to it.' },
      { word: 'function', definition: 'The function of something is what it does.' },
      { word: 'grass', definition: 'Grass is the green leaves that cover the ground.' },
      { word: 'guard', definition: 'To guard something is to take care of it.' },
      { word: 'image', definition: 'The image of something is a picture of it.' },
      { word: 'immediate', definition: 'If something is immediate, it happens quickly.' },
      { word: 'primary', definition: 'If something is primary, it is the most important thing.' },
      { word: 'proud', definition: 'If someone feels proud, they are happy about what they have done.' },
      { word: 'remain', definition: 'To remain somewhere is to stay there.' },
      { word: 'rest', definition: 'To rest is to stop being active while the body gets back its strength.' },
      { word: 'separate', definition: 'If two things are separate, they are not together.' },
      { word: 'site', definition: 'A site is a place.' },
      { word: 'tail', definition: 'A tail is a part of an animal\'s body, sticking out from its rear or back.' },
      { word: 'trouble', definition: 'Trouble is a problem or a difficulty.' },
    ],
  },
  {
    unit: 11,
    words: [
      { word: 'anymore', definition: 'Anymore means any longer.' },
      { word: 'asleep', definition: 'When a person is asleep, they are not awake.' },
      { word: 'berry', definition: 'A berry is a small round fruit that grows on certain plants and trees.' },
      { word: 'collect', definition: 'To collect things is to group them together all in one place.' },
      { word: 'compete', definition: 'To compete is to try to be better than someone.' },
      { word: 'conversation', definition: 'A conversation is a talk between people.' },
      { word: 'creature', definition: 'A creature is any living thing.' },
      { word: 'decision', definition: 'A decision is a choice.' },
      { word: 'either', definition: 'Either is used with "or" to say there are two or more possibilities.' },
      { word: 'forest', definition: 'A forest is a place with lots of trees and animals.' },
      { word: 'ground', definition: 'The ground is the top part of the Earth that we walk on.' },
      { word: 'introduce', definition: 'To introduce someone or something is to say who they are.' },
      { word: 'marry', definition: 'To marry is to legally become husband and wife.' },
      { word: 'prepare', definition: 'To prepare is to get ready for something.' },
      { word: 'sail', definition: 'To sail is to move a boat on the water.' },
      { word: 'serious', definition: 'When something is serious, it is bad or unsafe.' },
      { word: 'spend', definition: 'To spend is to use time doing something or being somewhere.' },
      { word: 'strange', definition: 'When something is strange, it is not normal.' },
      { word: 'truth', definition: 'The truth is a fact or something that is right.' },
      { word: 'wake', definition: 'To wake is to not be sleeping anymore.' },
    ],
  },
  {
    unit: 12,
    words: [
      { word: 'alone', definition: 'If someone is alone, they are not with another person.' },
      { word: 'apartment', definition: 'An apartment is a set of rooms in a building where people live.' },
      { word: 'article', definition: 'An article is a story in a newspaper or magazine.' },
      { word: 'artist', definition: 'An artist is a person who paints, draws, or makes sculptures.' },
      { word: 'attitude', definition: 'Someone\'s attitude is the way they feel and think.' },
      { word: 'compare', definition: 'To compare means to say how two things are the same and different.' },
      { word: 'judge', definition: 'To judge something is to say if it is good or bad.' },
      { word: 'magazine', definition: 'A magazine is a regular publication with news, stories, and articles.' },
      { word: 'material', definition: 'A material is what is used to make something.' },
      { word: 'meal', definition: 'A meal is a time when food is eaten like breakfast, lunch, or dinner.' },
      { word: 'method', definition: 'A method is the way to do something.' },
      { word: 'neighbor', definition: 'A neighbor is a person who lives near you.' },
      { word: 'professional', definition: 'If something is professional, it deals with work that uses special skills.' },
      { word: 'profit', definition: 'A profit is the extra money you make when you sell something.' },
      { word: 'quality', definition: 'The quality of something is how good it is.' },
      { word: 'shape', definition: 'A shape is a simple form like a square or circle.' },
      { word: 'space', definition: 'A space is an empty area.' },
      { word: 'stair', definition: 'Stairs are the things that are used to go up in a building.' },
      { word: 'symbol', definition: 'A symbol is a thing that stands for something else.' },
      { word: 'thin', definition: 'If someone or something is thin, they are not fat.' },
    ],
  },
  {
    unit: 13,
    words: [
      { word: 'blood', definition: 'Blood is the red liquid in your body.' },
      { word: 'burn', definition: 'To burn something is to set it on fire.' },
      { word: 'cell', definition: 'A cell is a small room where a person is locked in.' },
      { word: 'contain', definition: 'To contain something is to have it inside.' },
      { word: 'correct', definition: 'To be correct is to be right.' },
      { word: 'crop', definition: 'A crop is food that a farmer grows.' },
      { word: 'demand', definition: 'To demand something is to say strongly that you want it.' },
      { word: 'equal', definition: 'To be equal is to be the same.' },
      { word: 'feed', definition: 'To feed is to give food.' },
      { word: 'hole', definition: 'A hole is an opening in something.' },
      { word: 'increase', definition: 'To increase something is to make it larger or more.' },
      { word: 'lord', definition: 'Long ago, a lord was a man in charge of a town.' },
      { word: 'owe', definition: 'To owe is to have to pay or give back something received from another.' },
      { word: 'position', definition: 'A position is the way something is placed.' },
      { word: 'raise', definition: 'To raise something is to lift it up.' },
      { word: 'responsible', definition: 'If a person is responsible, they do the right things.' },
      { word: 'sight', definition: 'A sight is something interesting to see.' },
      { word: 'spot', definition: 'A spot is a place where something happens.' },
      { word: 'structure', definition: 'A structure is a building.' },
      { word: 'whole', definition: 'Whole means all of something.' },
    ],
  },
  {
    unit: 14,
    words: [
      { word: 'coach', definition: 'A coach is a person who teaches sports.' },
      { word: 'control', definition: 'To control something is to make it do what you want.' },
      { word: 'description', definition: 'A description of someone or something says what they are like.' },
      { word: 'direct', definition: 'If something is direct, it goes straight between two places.' },
      { word: 'exam', definition: 'An exam is a test.' },
      { word: 'example', definition: 'An example of something is a thing that is typical of it.' },
      { word: 'limit', definition: 'A limit is the largest or smallest amount of something that you allow.' },
      { word: 'local', definition: 'If something is local, it is nearby.' },
      { word: 'magical', definition: 'Magical describes a quality that makes someone or something special.' },
      { word: 'mail', definition: 'Mail is letters and other things sent to people.' },
      { word: 'novel', definition: 'A novel is a book that tells a story.' },
      { word: 'outline', definition: 'An outline is the plan for a story or essay.' },
      { word: 'poet', definition: 'A poet is a person who writes poems.' },
      { word: 'print', definition: 'To print something is to put it onto paper.' },
      { word: 'scene', definition: 'A scene is one part of a book or movie.' },
      { word: 'sheet', definition: 'A sheet is a thin flat piece of paper.' },
      { word: 'silly', definition: 'If someone or something is silly, they show a lack of thought.' },
      { word: 'store', definition: 'A store is a place where you can buy things.' },
      { word: 'suffer', definition: 'To suffer is to feel pain.' },
      { word: 'technology', definition: 'Technology is new things made by using science.' },
    ],
  },
  {
    unit: 15,
    words: [
      { word: 'across', definition: 'To go across something is to go to the other side of it.' },
      { word: 'breathe', definition: 'To breathe means to let air go in and out of your body.' },
      { word: 'characteristic', definition: 'A characteristic is something that shows what a person or a thing is like.' },
      { word: 'consume', definition: 'To consume something means to eat or drink it.' },
      { word: 'excite', definition: 'To excite someone means to make them happy and interested.' },
      { word: 'extreme', definition: 'If something is extreme, it is in a large amount or degree.' },
      { word: 'fear', definition: 'Fear is the feeling of being afraid.' },
      { word: 'fortunate', definition: 'If you are fortunate, you are lucky.' },
      { word: 'happen', definition: 'If someone happens to do something, they do it by chance.' },
      { word: 'length', definition: 'The length of something is how long it is from one end to the other.' },
      { word: 'mistake', definition: 'A mistake is something you do wrong.' },
      { word: 'observe', definition: 'To observe something is to watch it.' },
      { word: 'opportunity', definition: 'An opportunity is a chance to do something.' },
      { word: 'prize', definition: 'A prize is something of value that is given to the winner.' },
      { word: 'race', definition: 'A race is a contest to see who is the fastest.' },
      { word: 'realize', definition: 'To realize is to suddenly understand.' },
      { word: 'respond', definition: 'To respond is to give an answer to what someone else said.' },
      { word: 'risk', definition: 'A risk is a chance of something bad happening.' },
      { word: 'wonder', definition: 'To wonder is to ask yourself questions or have a need to know.' },
      { word: 'yet', definition: 'Yet is used to say something has not happened up to now.' },
    ],
  },
  {
    unit: 16,
    words: [
      { word: 'academy', definition: 'An academy is a special type of school.' },
      { word: 'ancient', definition: 'If something is ancient, it is very old.' },
      { word: 'board', definition: 'A board is a flat piece of wood.' },
      { word: 'century', definition: 'A century is one hundred years.' },
      { word: 'clue', definition: 'A clue is a fact or object that helps solve a mystery or crime.' },
      { word: 'concert', definition: 'A concert is an event where you listen to people play music.' },
      { word: 'county', definition: 'A county is the largest political division of a state in the US.' },
      { word: 'dictionary', definition: 'A dictionary is a book that tells you what words mean.' },
      { word: 'exist', definition: 'To exist is to be real.' },
      { word: 'flat', definition: 'Flat describes something that is level and smooth with no curved parts.' },
      { word: 'gentleman', definition: 'A gentleman is a nice man.' },
      { word: 'hidden', definition: 'Hidden means to be not easily noticed or too hard to find.' },
      { word: 'maybe', definition: 'Maybe is used to show that something is possible or may be true.' },
      { word: 'officer', definition: 'An officer is a leader in the army.' },
      { word: 'original', definition: 'If something is original, it is the first one of that thing.' },
      { word: 'pound', definition: 'To pound something is to hit it many times with a lot of force.' },
      { word: 'process', definition: 'A process is the steps to take to do something.' },
      { word: 'publish', definition: 'To publish a book is to get it printed and ready to sell.' },
      { word: 'theater', definition: 'A theater is a building where you watch plays, shows, and movies.' },
      { word: 'wealth', definition: 'Wealth is a large amount of money.' },
    ],
  },
  {
    unit: 17,
    words: [
      { word: 'appreciate', definition: 'To appreciate something is to understand its good qualities.' },
      { word: 'available', definition: 'If something is available, it means you can get it.' },
      { word: 'beat', definition: 'To beat someone means to do better than they do.' },
      { word: 'bright', definition: 'If something is bright, it shows a lot of light.' },
      { word: 'celebrate', definition: 'To celebrate is to do something to show that an event is special.' },
      { word: 'determine', definition: 'To determine means to choose or make a decision.' },
      { word: 'disappear', definition: 'To disappear means to go away or not be seen.' },
      { word: 'else', definition: 'If you talk about something else, you talk about something different.' },
      { word: 'fair', definition: 'Fair describes treating someone in a way that is reasonable or right.' },
      { word: 'flow', definition: 'To flow is to move easily and continuously in one direction.' },
      { word: 'forward', definition: 'If you move forward, you move in the direction in front of you.' },
      { word: 'hill', definition: 'A hill is a round area of land. It is higher than the land around it.' },
      { word: 'level', definition: 'A level is a point on a scale that measures something.' },
      { word: 'lone', definition: 'If someone or something is lone, they are the only one of that kind.' },
      { word: 'puddle', definition: 'A puddle is a pool of liquid on the ground.' },
      { word: 'response', definition: 'A response is the answer to a question.' },
      { word: 'season', definition: 'A season is a time of the year: spring, summer, fall or winter.' },
      { word: 'solution', definition: 'A solution is a way to solve a problem.' },
      { word: 'waste', definition: 'To waste means to carelessly use something all up.' },
      { word: 'whether', definition: 'You use whether when you must choose between two things.' },
    ],
  },
  {
    unit: 18,
    words: [
      { word: 'argue', definition: 'To argue is to angrily speak to someone because you do not agree.' },
      { word: 'communicate', definition: 'To communicate is to give information by talking, writing, etc.' },
      { word: 'crowd', definition: 'A crowd is a large group of people.' },
      { word: 'depend', definition: 'To depend on someone or something is to need them.' },
      { word: 'dish', definition: 'A dish is a plate.' },
      { word: 'empty', definition: 'If something is empty, it does not have anything in it.' },
      { word: 'exact', definition: 'If something is exact, it is just the right amount.' },
      { word: 'fresh', definition: 'If something is fresh, it is new.' },
      { word: 'gather', definition: 'To gather is to collect several things usually from different places.' },
      { word: 'indicate', definition: 'To indicate means to show, point or make something clear.' },
      { word: 'item', definition: 'An item is a thing that you buy or sell.' },
      { word: 'offer', definition: 'To offer is to present someone with something.' },
      { word: 'price', definition: 'The price of something is how much it costs.' },
      { word: 'product', definition: 'A product is something that is made.' },
      { word: 'property', definition: 'Property is something that someone owns.' },
      { word: 'purchase', definition: 'To purchase something is to buy it.' },
      { word: 'recommend', definition: 'To recommend something is to say that someone should do it.' },
      { word: 'select', definition: 'To select something is to choose it.' },
      { word: 'tool', definition: 'A tool is something that helps you do a task.' },
      { word: 'treat', definition: 'To treat is to act in a certain way toward someone.' },
    ],
  },
  {
    unit: 19,
    words: [
      { word: 'alive', definition: 'If someone or something is alive, they are not dead.' },
      { word: 'bone', definition: 'A bone is a hard part of the body.' },
      { word: 'bother', definition: 'To bother is to make the effort to do something.' },
      { word: 'captain', definition: 'A captain is the person who leads a ship or airplane.' },
      { word: 'conclusion', definition: 'The conclusion of something is the final part of it.' },
      { word: 'doubt', definition: 'Doubt is a feeling of not being sure.' },
      { word: 'explore', definition: 'To explore is to look for new places.' },
      { word: 'foreign', definition: 'If something is foreign, it is from a different country.' },
      { word: 'glad', definition: 'If you are glad, you are happy.' },
      { word: 'however', definition: 'However means despite or not being influenced by something.' },
      { word: 'injustice', definition: 'Injustice is a lack of fairness or justice.' },
      { word: 'international', definition: 'If something is international, it involves more than one country.' },
      { word: 'lawyer', definition: 'A lawyer works with the law and represents people in court.' },
      { word: 'mention', definition: 'To mention something is to talk about it.' },
      { word: 'policy', definition: 'A policy is a rule.' },
      { word: 'social', definition: 'If something is social, it is about many people in a community.' },
      { word: 'speech', definition: 'A speech is something said to a group of people.' },
      { word: 'staff', definition: 'A staff is a group of people working together in a company.' },
      { word: 'toward', definition: 'If you go toward something, you go closer to it.' },
      { word: 'wood', definition: 'Wood is the thing that trees are made of.' },
    ],
  },
  {
    unit: 20,
    words: [
      { word: 'achieve', definition: 'To achieve something is to successfully do it after trying hard.' },
      { word: 'advise', definition: 'To advise someone is to tell them what to do.' },
      { word: 'already', definition: 'If something happens already, it happens before a certain time.' },
      { word: 'basic', definition: 'If something is basic, it is very simple or easy.' },
      { word: 'bit', definition: 'A bit is a small amount of something.' },
      { word: 'consider', definition: 'To consider something means to think about it.' },
      { word: 'destroy', definition: 'To destroy means to damage something so badly that it cannot be used.' },
      { word: 'entertain', definition: 'To entertain someone is to do something that they enjoy.' },
      { word: 'extra', definition: 'If something is extra, it is more than what is needed.' },
      { word: 'goal', definition: 'A goal is something you work toward.' },
      { word: 'lie', definition: 'To lie is to say or write something untrue to deceive someone.' },
      { word: 'meat', definition: 'Meat is food made of animals.' },
      { word: 'opinion', definition: 'An opinion is a thought about a person or a thing.' },
      { word: 'real', definition: 'If something is real, it actually exists.' },
      { word: 'reflect', definition: 'To reflect is when a surface sends back light, heat, sound or an image.' },
      { word: 'regard', definition: 'To regard someone or something is to think of them in a certain way.' },
      { word: 'serve', definition: 'To serve someone is to give them food or drinks.' },
      { word: 'vegetable', definition: 'A vegetable is a plant used as food.' },
      { word: 'war', definition: 'A war is a big fight between two groups of people.' },
      { word: 'worth', definition: 'If something is worth an amount of money, it costs that amount.' },
    ],
  },
  {
    unit: 21,
    words: [
      { word: 'appear', definition: 'To appear is to seem.' },
      { word: 'base', definition: 'The base is the bottom of something.' },
      { word: 'brain', definition: 'The brain is the organ in your head that lets you think.' },
      { word: 'career', definition: 'A career is a job that you do for a large part of your life.' },
      { word: 'clerk', definition: 'A clerk is a type of worker. Clerks in a store help customers.' },
      { word: 'effort', definition: 'Effort is hard work or an attempt to do something.' },
      { word: 'enter', definition: 'To enter a place is to go into it.' },
      { word: 'excellent', definition: 'When something is excellent, it is very good.' },
      { word: 'hero', definition: 'A hero is a brave person who does things to help others.' },
      { word: 'hurry', definition: 'To hurry is to do something quickly.' },
      { word: 'inform', definition: 'To inform someone is to tell them about something.' },
      { word: 'later', definition: 'Later means after the present, expected, or usual time.' },
      { word: 'leave', definition: 'To leave means to go away from someone or something.' },
      { word: 'locate', definition: 'To locate something is to find it.' },
      { word: 'nurse', definition: 'A nurse is a person who helps sick people in the hospital.' },
      { word: 'operation', definition: 'An operation is when a doctor replaces or removes something in the body.' },
      { word: 'pain', definition: 'Pain is the feeling that you have when you are hurt.' },
      { word: 'refuse', definition: 'To refuse something is to say "no" to it.' },
      { word: 'though', definition: 'Though is used when the second idea makes the first seem surprising.' },
      { word: 'various', definition: 'If something is various, there are many types of it.' },
    ],
  },
  {
    unit: 22,
    words: [
      { word: 'actual', definition: 'Actual means that something is real or true.' },
      { word: 'amaze', definition: 'To amaze someone is to surprise them very much.' },
      { word: 'charge', definition: 'A charge is the price to pay for something.' },
      { word: 'comfort', definition: 'To comfort someone means to make them feel better.' },
      { word: 'contact', definition: 'To contact someone is to speak or write to them.' },
      { word: 'customer', definition: 'A customer is a person who buys something at a store.' },
      { word: 'deliver', definition: 'To deliver something is to take it from one place to another.' },
      { word: 'earn', definition: 'To earn means to get money for the work you do.' },
      { word: 'gate', definition: 'A gate is a type of door. Gates are usually made of metal or wood.' },
      { word: 'include', definition: 'To include something means to have it as part of a group.' },
      { word: 'manage', definition: 'To manage something means to control or be in charge of it.' },
      { word: 'mystery', definition: 'A mystery is something that is difficult to understand or explain.' },
      { word: 'occur', definition: 'To occur means to happen.' },
      { word: 'opposite', definition: 'If A is the opposite of B, A is completely different from B.' },
      { word: 'plate', definition: 'A plate is a flat round thing that you put food on.' },
      { word: 'receive', definition: 'To receive something is to get it.' },
      { word: 'reward', definition: 'A reward is something given in exchange for good behavior or work.' },
      { word: 'set', definition: 'To set something is to put it somewhere.' },
      { word: 'steal', definition: 'To steal is to take something that is not yours.' },
      { word: 'thief', definition: 'A thief is someone who quietly takes things that do not belong to them.' },
    ],
  },
  {
    unit: 23,
    words: [
      { word: 'advance', definition: 'To advance is to go forward.' },
      { word: 'athlete', definition: 'An athlete is a person who plays sports.' },
      { word: 'average', definition: 'If something is average, it is at a normal level.' },
      { word: 'behavior', definition: 'Your behavior is the way you act.' },
      { word: 'behind', definition: 'Behind means to be at the back of something.' },
      { word: 'course', definition: 'A course is a class in school.' },
      { word: 'lower', definition: 'To lower something is to make it go down.' },
      { word: 'match', definition: 'To match is to be the same or similar.' },
      { word: 'member', definition: 'A member is a person who is part of a group.' },
      { word: 'mental', definition: 'If something is mental, it has to do with your mind.' },
      { word: 'passenger', definition: 'A passenger is a person who rides in a car, train, or airplane.' },
      { word: 'personality', definition: 'Your personality is what you are like and how you behave.' },
      { word: 'poem', definition: 'A poem is a short kind of writing.' },
      { word: 'pole', definition: 'A pole is a long thin stick made of wood or metal that supports things.' },
      { word: 'remove', definition: 'To remove something is to take it away.' },
      { word: 'safety', definition: 'Safety means to be the condition of being safe and free from danger.' },
      { word: 'shoot', definition: 'To shoot is to fire something like a bullet at someone or something.' },
      { word: 'sound', definition: 'To sound means to make a noise.' },
      { word: 'swim', definition: 'To swim is to move through water.' },
      { word: 'web', definition: 'A web is a home made by a spider.' },
    ],
  },
  {
    unit: 24,
    words: [
      { word: 'block', definition: 'A block is a solid piece of wood, stone or ice.' },
      { word: 'cheer', definition: 'To cheer is to give a loud shout of approval or encouragement.' },
      { word: 'complex', definition: 'If something is complex, it has many small parts. It is hard to understand.' },
      { word: 'critic', definition: 'A critic is someone who give their opinions about movies, books, plays.' },
      { word: 'event', definition: 'An event is something that happens, especially something important.' },
      { word: 'exercise', definition: 'To exercise is to run or play sports so that you can be healthy.' },
      { word: 'fit', definition: 'If something fits, it is small enough or the right size to go there.' },
      { word: 'friendship', definition: 'Friendship is the relationship between people who are friends.' },
      { word: 'guide', definition: 'A guide is someone who shows you where to go.' },
      { word: 'lack', definition: 'If there is a lack of something, there is not enough of it.' },
      { word: 'passage', definition: 'A passage is a long area with walls that goes from one place to another.' },
      { word: 'perform', definition: 'To perform is to do something in front of people who watch.' },
      { word: 'pressure', definition: 'Pressure is what you apply to make someone do something.' },
      { word: 'probable', definition: 'If something is probable, it is likely to happen.' },
      { word: 'public', definition: 'If something is public, it is meant for everyone to use.' },
      { word: 'strike', definition: 'To strike someone or something is to hit them.' },
      { word: 'support', definition: 'To support something is to like it and help it be successful.' },
      { word: 'task', definition: 'A task is work that someone has to do.' },
      { word: 'term', definition: 'A term is a word for something.' },
      { word: 'unite', definition: 'To unite is to get together to do something.' },
    ],
  },
  {
    unit: 25,
    words: [
      { word: 'associate', definition: 'To associate means to connect something with a person or thing.' },
      { word: 'environment', definition: 'The environment is the place where people work or live.' },
      { word: 'factory', definition: 'A factory is a building where things are made or put together.' },
      { word: 'feature', definition: 'A feature is an important part of something.' },
      { word: 'instance', definition: 'An instance is an example of something.' },
      { word: 'involve', definition: 'To involve means to be actively taking part in something.' },
      { word: 'medicine', definition: 'Medicine is something you take to feel better or treat an illness.' },
      { word: 'mix', definition: 'A mix is different things put together.' },
      { word: 'organize', definition: 'To organize is to plan or get ready for an event.' },
      { word: 'period', definition: 'A period is an amount of time when something happens.' },
      { word: 'populate', definition: 'If people populate an area, they live there.' },
      { word: 'produce', definition: 'To produce something is to make or grow it.' },
      { word: 'range', definition: 'A range is a number or a set of similar things.' },
      { word: 'recognize', definition: 'To recognize something is to know it because you have seen it before.' },
      { word: 'regular', definition: 'If something is regular, it happens often and in equal amounts of time.' },
      { word: 'sign', definition: 'A sign is a notice giving information, directions, a warning, etc.' },
      { word: 'tip', definition: 'A tip is a pointed end of something.' },
      { word: 'tradition', definition: 'A tradition is something people have been doing for a long time.' },
      { word: 'trash', definition: 'Trash is waste material or unwanted or worthless things.' },
      { word: 'wide', definition: 'If something is wide, it is large from side to side.' },
    ],
  },
  {
    unit: 26,
    words: [
      { word: 'advice', definition: 'Advice is an opinion about what to do.' },
      { word: 'along', definition: 'Along means to move from one part of a road, river, etc. to another.' },
      { word: 'attention', definition: 'Attention is the notice, thought, or consideration of someone.' },
      { word: 'attract', definition: 'To attract means to make a person or thing come closer or be interested.' },
      { word: 'climb', definition: 'To climb means to use your hands and feet to go up on something.' },
      { word: 'drop', definition: 'To drop is to fall or allow something to fall.' },
      { word: 'final', definition: 'If something is final, it is the last part.' },
      { word: 'further', definition: 'Further is used to say something is from a distance or time.' },
      { word: 'imply', definition: 'To imply something is to suggest it without saying it.' },
      { word: 'maintain', definition: 'To maintain means to make something stay the same.' },
      { word: 'neither', definition: 'You use neither to connect two negative statements.' },
      { word: 'otherwise', definition: 'Otherwise means different or in another way.' },
      { word: 'physical', definition: 'If something is physical, it is related to your body and not your mind.' },
      { word: 'prove', definition: 'To prove something is to show that it is true.' },
      { word: 'react', definition: 'To react is to act in a certain way because of something that happened.' },
      { word: 'ride', definition: 'To ride something is to travel on it. You can ride an animal, a bike, etc.' },
      { word: 'situated', definition: 'If something is situated somewhere, it is in that place.' },
      { word: 'society', definition: 'Society is people and the way that they live.' },
      { word: 'standard', definition: 'A standard is what people consider normal or good.' },
      { word: 'suggest', definition: 'To suggest something means to give an idea or plan about it.' },
    ],
  },
  {
    unit: 27,
    words: [
      { word: 'actually', definition: 'Actually means in fact or really.' },
      { word: 'bite', definition: 'Bite is the act of using your teeth to cut and tear into something.' },
      { word: 'coast', definition: 'The coast is the land by an ocean.' },
      { word: 'deal', definition: 'A deal is an agreement that you have with another person.' },
      { word: 'desert', definition: 'The desert is an area of land without many plants or water.' },
      { word: 'earthquake', definition: 'An earthquake is a shaking movement of the ground.' },
      { word: 'effective', definition: 'If something is effective, it works well.' },
      { word: 'examine', definition: 'To examine something is to look at it carefully.' },
      { word: 'false', definition: 'If something is false, it is not correct.' },
      { word: 'gift', definition: 'A gift is something you give someone.' },
      { word: 'hunger', definition: 'Hunger is the feeling that you get when you need to eat.' },
      { word: 'imagine', definition: 'To imagine something is to think of it in your mind.' },
      { word: 'journey', definition: 'A journey is a long trip.' },
      { word: 'puzzle', definition: 'A puzzle is something that is hard to understand.' },
      { word: 'quite', definition: 'Quite is used to say that something is complete or very much.' },
      { word: 'rather', definition: 'Rather is used when you want to do one thing but not the other.' },
      { word: 'specific', definition: 'If something is specific, it is precise or exact.' },
      { word: 'tour', definition: 'A tour is a short trip in which you see many sights.' },
      { word: 'trip', definition: 'A trip is a journey to a certain place.' },
      { word: 'value', definition: 'If something has value, it is worth a lot of money.' },
    ],
  },
  {
    unit: 28,
    words: [
      { word: 'band', definition: 'A band is a group of people who play music.' },
      { word: 'barely', definition: 'Barely means by the smallest amount, almost not.' },
      { word: 'boring', definition: 'If something is boring, it is not fun.' },
      { word: 'cancel', definition: 'To cancel means to decide that an event or a request will not happen.' },
      { word: 'driveway', definition: 'A driveway is a short private road that leads to a person\'s home.' },
      { word: 'garbage', definition: 'Garbage is waste material like unwanted or spoiled food, bottles, paper, etc.' },
      { word: 'instrument', definition: 'An instrument is something designed to do a certain task like music.' },
      { word: 'list', definition: 'A list is a record of information printed with an item on each line.' },
      { word: 'magic', definition: 'Magic is the power to do impossible things.' },
      { word: 'message', definition: 'A message is a set of words that you send to someone.' },
      { word: 'notice', definition: 'To notice something is to see it for the first time.' },
      { word: 'own', definition: 'To own something means to have it. That thing belongs to you.' },
      { word: 'predict', definition: 'To predict something is to say that it will happen.' },
      { word: 'professor', definition: 'A professor is a person who teaches in college.' },
      { word: 'rush', definition: 'To rush is to go somewhere or do something very quickly.' },
      { word: 'schedule', definition: 'A schedule is a plan that tells you when to do things.' },
      { word: 'share', definition: 'To share something is to give some of it to another person.' },
      { word: 'stage', definition: 'A stage is a place where actors or musicians act or sing.' },
      { word: 'storm', definition: 'A storm is very bad weather. There is a lot of rain or snow.' },
      { word: 'within', definition: 'You use within to say that something is inside another thing.' },
    ],
  },
  {
    unit: 29,
    words: [
      { word: 'advertise', definition: 'To advertise is to tell people about something on TV, radio, etc.' },
      { word: 'assign', definition: 'To assign something to someone is to tell them to do it.' },
      { word: 'audience', definition: 'An audience is a group of people who watch something together.' },
      { word: 'breakfast', definition: 'Breakfast is the first meal of the day.' },
      { word: 'competition', definition: 'A competition is a contest to see who is the best at something.' },
      { word: 'cool', definition: 'If the weather is cool, it is a little bit cold.' },
      { word: 'gain', definition: 'If you gain something, you get more of it.' },
      { word: 'importance', definition: 'Importance means the quality or condition of being needed or valued.' },
      { word: 'knowledge', definition: 'Knowledge is information that you have about something.' },
      { word: 'major', definition: 'If something is major, it is big or important.' },
      { word: 'mean', definition: 'Mean describes someone who is unkind or cruel.' },
      { word: 'prefer', definition: 'If you prefer something, you want it more than something else.' },
      { word: 'president', definition: 'A president is the leader of a country.' },
      { word: 'progress', definition: 'Progress is the act of getting closer to doing or finishing something.' },
      { word: 'respect', definition: 'Respect is a good opinion of someone because they are good.' },
      { word: 'rich', definition: 'If you are rich, you have a lot of money.' },
      { word: 'skill', definition: 'A skill is the knowledge and ability that allows you to do something well.' },
      { word: 'somehow', definition: 'Somehow means in a way or by some means which is not known.' },
      { word: 'strength', definition: 'Strength is the physical power that you have.' },
      { word: 'vote', definition: 'To vote is to officially choose between two or more things.' },
    ],
  },
  {
    unit: 30,
    words: [
      { word: 'above', definition: 'If something is above, it is at a higher level than something else.' },
      { word: 'ahead', definition: 'If something is ahead of something else, it is in front of it.' },
      { word: 'amount', definition: 'An amount is how much there is of something.' },
      { word: 'belief', definition: 'A belief is a strong feeling that something is correct or true.' },
      { word: 'center', definition: 'The center of something is the middle of it.' },
      { word: 'common', definition: 'If something is common, it happens often or there is much of it.' },
      { word: 'cost', definition: 'To cost is to require expenditure or payment.' },
      { word: 'demonstrate', definition: 'To demonstrate something is to show how it is done.' },
      { word: 'different', definition: 'Different describes someone or something that is not the same as others.' },
      { word: 'evidence', definition: 'Evidence is a fact or thing that you use to prove something.' },
      { word: 'honesty', definition: 'Honesty means the quality of being truthful or honest.' },
      { word: 'idiom', definition: 'An idiom is a phrase with a meaning different from its words.' },
      { word: 'independent', definition: 'If something is independent, it is not controlled by something else.' },
      { word: 'inside', definition: 'Inside means the inner part, space or side of something.' },
      { word: 'master', definition: 'A master is a person who is very good at something.' },
      { word: 'memory', definition: 'A memory is something you remember.' },
      { word: 'proper', definition: 'If something is proper, it is right.' },
      { word: 'scan', definition: 'To scan something is to look at it very carefully.' },
      { word: 'section', definition: 'A section is a part of something larger.' },
      { word: 'surface', definition: 'The surface of something is the top part or outside of it.' },
    ],
  },
];
